In [1]:
import numpy as np

## ndim shape size

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.size

10

In [9]:
A = np.ones(shape=(3,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
A.ndim

2

In [11]:
A.shape

(3, 5)

In [12]:
A.size

15

In [14]:
X = np.array([[1,2,3],
             [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
X.shape

(2, 3)

In [16]:
a = np.array([[1,2,3],
             [4,5]])
a.ndim

1

In [17]:
a.shape

(2,)

In [18]:
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [20]:
a.size # 并不是5

2

## reshape

In [21]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
X = a.reshape(2,5)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
X.ndim

2

In [27]:
X.shape

(2, 5)

In [28]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
a.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
# a.reshape(-1,3) # ValueError: cannot reshape array of size 10 into shape (3)

ValueError: cannot reshape array of size 10 into shape (3)

## 取值

In [32]:
X = np.arange(15).reshape(3,5)

In [33]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
X[0]

array([0, 1, 2, 3, 4])

In [35]:
X[-1]

array([10, 11, 12, 13, 14])

In [36]:
X[0][1]

1

In [37]:
X[(0,1)]

1

In [38]:
X[0,1]

1

## 切片

In [39]:
a = np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[0:5]

array([0, 1, 2, 3, 4])

In [42]:
a[:5]

array([0, 1, 2, 3, 4])

In [43]:
a[5:]

array([5, 6, 7, 8, 9])

In [44]:
a[0:8:2]

array([0, 2, 4, 6])

In [45]:
a[::2]

array([0, 2, 4, 6, 8])

In [46]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组切片

In [47]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
X[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [49]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [50]:
X[:2][:3] # 先切出[0:2]  再在前一次的结果上，再做[0:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
X2 = X[:2]

In [52]:
X2[:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [54]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## 引用关系

In [55]:
a = list(range(5))

In [56]:
a

[0, 1, 2, 3, 4]

In [57]:
b = a[:2]

In [58]:
b

[0, 1]

In [59]:
b[1] = 111
b

[0, 111]

In [60]:
a

[0, 1, 2, 3, 4]

In [61]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
X2 = X[:2,:2]

In [63]:
X2

array([[0, 1],
       [5, 6]])

In [64]:
X2[0,0] = 99
X2

array([[99,  1],
       [ 5,  6]])

In [65]:
X

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
X3 = X[:2,:2].copy()
X3

array([[99,  1],
       [ 5,  6]])

In [67]:
X3[0,0]=100
X3

array([[100,   1],
       [  5,   6]])

In [68]:
X

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])