In [1]:
import numpy as np

In [2]:
x = np.random.random(100)
x

array([0.39552751, 0.36867615, 0.95343765, 0.19900144, 0.37325718,
       0.3458819 , 0.70101529, 0.40811903, 0.28833759, 0.65781739,
       0.98681341, 0.62390692, 0.13839317, 0.91511356, 0.52630914,
       0.20079114, 0.05519478, 0.35252743, 0.203876  , 0.04389147,
       0.27132562, 0.59231824, 0.88926153, 0.6886198 , 0.61989559,
       0.00963013, 0.3329762 , 0.49196658, 0.59987825, 0.84183301,
       0.21890884, 0.70477549, 0.9894576 , 0.37155247, 0.53541267,
       0.54830491, 0.44661386, 0.60875961, 0.57597288, 0.04725481,
       0.51075155, 0.33580332, 0.04818844, 0.61179011, 0.22611077,
       0.78130042, 0.34883246, 0.85706989, 0.93775014, 0.6014553 ,
       0.14727721, 0.08428892, 0.15954331, 0.9299441 , 0.76697083,
       0.00243809, 0.19823957, 0.59507802, 0.86889873, 0.06788976,
       0.54237813, 0.14522219, 0.76889635, 0.3863426 , 0.15139292,
       0.57670767, 0.17796982, 0.59682661, 0.3000004 , 0.64806814,
       0.35920348, 0.80618756, 0.02734986, 0.28852415, 0.70419

In [3]:
sum(x)

46.82003688470414

In [4]:
np.sum(x)

46.82003688470414

In [5]:
arr = np.random.rand(10**7)

In [6]:
%timeit sum(arr)

1.41 s ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit np.sum(arr)

17.6 ms ± 380 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
np.min(x)

0.00243808899731901

In [9]:
np.max(x)

0.9894576025521881

In [10]:
x.sum()

46.82003688470414

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [17]:
np.prod(X+1)

2004189184

In [18]:
np.prod(X+1, axis=1)

array([   24,  1680, 11880, 43680])

In [19]:
X + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
np.mean(X)

7.5

In [21]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.mean(X, axis=0)

array([6., 7., 8., 9.])

In [23]:
np.median(X, axis=0)

array([6., 7., 8., 9.])

In [24]:
x = np.array([6600,5200,6300,5800,7100,90000])

In [25]:
np.mean(x)

20166.666666666668

In [26]:
np.median(x)

6450.0

In [27]:
np.percentile(x, q=50)

6450.0

In [28]:
np.percentile(x,q=100)

90000.0

In [29]:
np.max(x)

90000

In [30]:
for i in [0,25,50,75,100]:
    print(i, np.percentile(x,i))

0 5200.0
25 5925.0
50 6450.0
75 6975.0
100 90000.0


In [31]:
np.var(x)

975695555.5555555

In [32]:
np.sum((x - np.mean(x))**2)/np.size(x)

975695555.5555555

In [33]:
np.std(x)

31236.125808998073

In [34]:
np.var(x) ** 0.5

31236.125808998073

In [35]:
x = np.random.normal(0,1,size=1000000)

In [36]:
np.mean(x)

-0.0007742638107008699

In [37]:
np.std(x)

1.000598857583646