In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
range(10)

range(0, 10)

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array(range(5,10,2))

array([5, 7, 9])

## np.arange

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [11]:
np.arange(2,20,0.3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3, 11.6,
       11.9, 12.2, 12.5, 12.8, 13.1, 13.4, 13.7, 14. , 14.3, 14.6, 14.9,
       15.2, 15.5, 15.8, 16.1, 16.4, 16.7, 17. , 17.3, 17.6, 17.9, 18.2,
       18.5, 18.8, 19.1, 19.4, 19.7])

## np.zeros

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.ones

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.full

In [19]:
np.full(10,99)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [20]:
np.full((3,5),99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [21]:
np.full((3,5),99.0)

array([[99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.]])

In [22]:
np.full((3,5),fill_value=99.0)

array([[99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.]])

## np.linspace

In [24]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [26]:
np.linspace(0,20,10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

## np.random

In [27]:
np.random.randint(0,10)

5

In [28]:
np.random.randint(0,10,5)

array([4, 8, 5, 9, 4])

In [29]:
np.random.randint(0,10,size=5)

array([2, 3, 4, 9, 4])

In [30]:
np.random.randint(0,10,size=(2,5))

array([[5, 3, 1, 7, 9],
       [5, 8, 4, 1, 9]])

In [31]:
np.random.random(5)

array([0.26356038, 0.43021508, 0.6618125 , 0.66721842, 0.3022081 ])

In [32]:
np.random.random((3,5))

array([[0.70854117, 0.1937969 , 0.90017463, 0.73959181, 0.29916824],
       [0.72710552, 0.661373  , 0.40355686, 0.55017486, 0.45012096],
       [0.15614474, 0.21541721, 0.02655864, 0.94954647, 0.3877147 ]])

In [33]:
np.random.normal(size=5)

array([-0.62609661, -0.93110534,  0.901054  , -1.37069695, -0.51689918])

In [34]:
np.random.normal(size=(3,5))

array([[ 1.20445436,  0.98568831, -0.50942846,  0.3941087 , -1.05176135],
       [ 1.21908168,  0.534139  ,  0.25265842,  1.72975375, -0.07613473],
       [ 0.29853714,  0.90460045, -0.34219886,  1.42617976,  0.02129695]])