## Numpy中的矩阵运算

In [2]:
import numpy as np

In [4]:
a = np.array([0,2,4])
a

array([0, 2, 4])

In [5]:
a *2

array([0, 4, 8])

In [6]:
a = [0,2,4]
a * 2

[0, 2, 4, 0, 2, 4]

In [7]:
import array
array.array('i',[0,2,4])*2

array('i', [0, 2, 4, 0, 2, 4])

In [8]:
[i * 2 for i in a]

[0, 4, 8]

In [9]:
res = []
for i in a:
    res.append(i*2)
res

[0, 4, 8]

In [10]:
data = range(10**6)
data

range(0, 1000000)

In [11]:
%%time
res = []
for i in data:
    res.append(i*2)
res

Wall time: 241 ms


In [12]:
%time res = [i*2 for i in data]

Wall time: 167 ms


In [13]:
arr = np.array(data)

In [14]:
%time res = arr * 2

Wall time: 22.5 ms


In [15]:
a = np.array([0,2,4])
a

array([0, 2, 4])

In [16]:
a + 2

array([2, 4, 6])

In [17]:
a - 2

array([-2,  0,  2])

In [18]:
a / 2

array([0., 1., 2.])

In [19]:
X = np.arange(1,16).reshape((3,5))

In [20]:
X.shape

(3, 5)

In [21]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
X +1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [23]:
X *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [24]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [25]:
X //2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [26]:
X **2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [27]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [28]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [30]:
np.abs(X-2)

array([[ 1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [31]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [32]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [33]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [34]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
from math import e
e ** 3

20.085536923187664

In [36]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [37]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [38]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [39]:
e ** 0.69314718

1.9999999988801092

In [40]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [41]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵之间的运算

In [43]:
A = np.arange(4).reshape(2,-1)

In [44]:
A

array([[0, 1],
       [2, 3]])

In [46]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [47]:
A + B

array([[10, 11],
       [12, 13]])

In [48]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [49]:
A * B

array([[ 0, 10],
       [20, 30]])

In [50]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [51]:
A

array([[0, 1],
       [2, 3]])

In [53]:
B = np.array([10,20,30,40]).reshape(2,-1)
B

array([[10, 20],
       [30, 40]])

In [54]:
A.dot(B)

array([[ 30,  40],
       [110, 160]])

## 矩阵的逆

In [56]:
A

array([[0, 1],
       [2, 3]])

In [57]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [58]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [59]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [60]:
A = np.arange(6).reshape(2,-1)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
# np.linalg.inv(A) # LinAlgError: Last 2 dimensions of the array must be square

LinAlgError: Last 2 dimensions of the array must be square

In [62]:
pinvA = np.linalg.pinv(A)
pinvA

array([[-0.77777778,  0.27777778],
       [-0.11111111,  0.11111111],
       [ 0.55555556, -0.05555556]])

In [63]:
A.dot(pinvA)

array([[ 1.00000000e+00, -1.38777878e-16],
       [ 3.10862447e-15,  1.00000000e+00]])

## 矩阵的转置

In [65]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])