In [2]:
import numpy as np

In [4]:
np.__version__

'1.14.0'

In [6]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
li[3]=33

In [8]:
li

[0, 1, 2, 33, 4, 5, 6, 7, 8, 9]

In [9]:
li[5] = 'Hello Python!'

In [10]:
li

[0, 1, 2, 33, 4, 'Hello Python!', 6, 7, 8, 9]

In [12]:
import array
arr = array.array('i',list(range(10)))
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[3]

3

In [16]:
arr[3]=33
arr

array('i', [0, 1, 2, 33, 4, 5, 6, 7, 8, 9])

In [17]:
# arr[5] = 'Hello Python' #TypeError: an integer is required (got type str)

TypeError: an integer is required (got type str)

## numpy.nparray

In [19]:
nparr = np.array(list(range(10)))

In [21]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(nparr)

numpy.ndarray

In [24]:
nparr.dtype

dtype('int32')

In [25]:
nparr[3]

3

In [26]:
nparr[3]=33

In [27]:
nparr

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9])

In [28]:
# nparr[5] = 'Hello' # ValueError: invalid literal for int() with base 10: 'Hello'

ValueError: invalid literal for int() with base 10: 'Hello'

In [29]:
nparr[5] = 55.8

In [30]:
nparr

array([ 0,  1,  2, 33,  4, 55,  6,  7,  8,  9])

In [31]:
nparr.dtype

dtype('int32')

In [32]:
nparr2 = np.array([1,2,3.0])

In [33]:
nparr2

array([1., 2., 3.])

In [34]:
nparr2.dtype

dtype('float64')

In [36]:
nparr3 = np.array([1,2,3], dtype=float)

In [37]:
nparr3.dtype

dtype('float64')

In [38]:
nparr3

array([1., 2., 3.])

In [40]:
def python_test(n):
    a = [i**2 for i in range(n)]
    b = [i**3 for i in range(n)]
    c = []
    for i in range(n):
        c.append(a[i]+b[i])
    return c

In [41]:
python_test(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [45]:
def numpy_test(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [46]:
numpy_test(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [47]:
%time res = python_test(10000000)

Wall time: 14.3 s


In [48]:
%time res = numpy_test(10000000)

Wall time: 423 ms
