# (三)、矩阵相关操作

In [3]:
import numpy as np

In [4]:
X = np.array([[1.2, 1.5, 1.8],
[1.3, 1.4, 1.9],
[1.1, 1.6, 1.7]])
y = np.array([5, 10, 9]).T

## 1.使用循环的方式计算每天的采购总金额

In [5]:
total = [0,0,0]
for a in range(0,len(X)):
    for b in range(0,len(X[a])):
        total[a]=total[a]+(X[a][b]*y[b])
total

[37.2, 37.599999999999994, 36.8]

## 2. 使用矩阵点乘来计算每天的采购总金额

In [6]:
np.sum(X*y, axis=1)

array([37.2, 37.6, 36.8])

## 3. 测试两种方式的性能

In [7]:
total = [0,0,0]
for a in range(0,len(X)):
    for b in range(0,len(X[a])):
        total[a]=total[a]+(X[a][b]*y[b])
%timeit total

35.9 ns ± 3.91 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [8]:
%timeit np.sum(X*y, axis=1)

8.41 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# (四)、矩阵逆

In [59]:
np.random.seed(1)
X = np.random.randint(1, 10, size=30)

In [60]:
X

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

## 请将X处理理为⼀一个3列列的矩阵

In [61]:
X = X.reshape(10,-1)
X

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

## 将第三列列中，小于等于3的修改为0、大于3且小于等于6的修改为1、大于6的修改为2

In [62]:
a = X[:,-1]
a[a<=3]=0
a[(a>3)&(a<=6)]=1
a[a>6]=2
X[:,-1]=a
X

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])

## 假设这是10条样本数据，前两列列是样本的两个特征，第3列列是样本的分类标记，请分离出样本的特征和分类标记，分别存放在两个变量量中，用 X_train 存放样本特征(红色部份), y_train 存放分类标记(绿色部份)

In [63]:
X_train, y_train = np.hsplit(X,[-1])
X_train

array([[6, 9],
       [1, 1],
       [8, 7],
       [5, 6],
       [5, 3],
       [8, 8],
       [8, 1],
       [8, 7],
       [1, 2],
       [9, 4]])

In [64]:
y_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2]])

## 请用numpy的比较运算，通过 y_train 中的数据，分离出 X_train 中的3个分类

In [107]:
w = []
for m in y_train:
    w.append(m[0]==0)
X_train[w,:]

array([[1, 1],
       [8, 7],
       [5, 6],
       [8, 8],
       [8, 7]])

In [108]:
w = []
for m in y_train:
    w.append(m[0]==1)
X_train[w,:]

array([[6, 9],
       [5, 3]])

In [109]:
w = []
for m in y_train:
    w.append(m[0]==2)
X_train[w,:]

array([[8, 1],
       [1, 2],
       [9, 4]])